// <copyright file="GPGSIds.cs" company="Google Inc.">
// Copyright (C) 2015 Google Inc. All Rights Reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//    limitations under the License.
// </copyright>

///
/// This file is automatically generated DO NOT EDIT!
///
/// These are the constants defined in the Play Games Console for Game Services
/// Resources.
///


public static class GPGSIds
{
        public const string achievement_interacta_con_un_npc_por_primera_vez = "CgkIu42z3rAdEAIQBA"; // <GPGSID>
        public const string achievement_compra_una_skin_por_primera_vez = "CgkIu42z3rAdEAIQBQ"; // <GPGSID>
        public const string achievement_consigue_5000_monedas = "CgkIu42z3rAdEAIQDg"; // <GPGSID>
        public const string achievement_consigue_3000_monedas = "CgkIu42z3rAdEAIQDA"; // <GPGSID>
        public const string achievement_consigue_1500_monedas = "CgkIu42z3rAdEAIQCQ"; // <GPGSID>
        public const string achievement_consigue_1000_monedas = "CgkIu42z3rAdEAIQCA"; // <GPGSID>
        public const string achievement_termina_el_nivel_3 = "CgkIu42z3rAdEAIQAw"; // <GPGSID>
        public const string achievement_consigue_2500_monedas = "CgkIu42z3rAdEAIQCw"; // <GPGSID>
        public const string achievement_termina_el_nivel_2 = "CgkIu42z3rAdEAIQAg"; // <GPGSID>
        public const string achievement_consigue_2000_monedas = "CgkIu42z3rAdEAIQCg"; // <GPGSID>
        public const string achievement_consigue_500_monedas = "CgkIu42z3rAdEAIQBw"; // <GPGSID>
        public const string achievement_obtn_una_moneda_por_primera_vez = "CgkIu42z3rAdEAIQBg"; // <GPGSID>
        public const string achievement_consigue_10000_monedas = "CgkIu42z3rAdEAIQDw"; // <GPGSID>
        public const string achievement_termina_el_nivel_1 = "CgkIu42z3rAdEAIQAQ"; // <GPGSID>
        public const string achievement_consigue_4000_monedas = "CgkIu42z3rAdEAIQDQ"; // <GPGSID>

}

